export interface CollectionResponse {
  banner_image_url: string | null;
  chat_url: string | null;
  created_date: string;
  default_to_fiat: boolean;
  description: string | null;
  dev_buyer_fee_basis_points: "number";
  dev_seller_fee_basis_points: "number";
  discord_url: string | null;
  display_data: { card_display_style: string; images: [any] };
  external_url: string | null;
  featured: boolean;
  featured_image_url: string | null;
  hidden: true;
  image_url: string | null;
  instagram_username: string | null;
  is_nsfw: boolean;
  is_subject_to_whitelist: boolean;
  large_image_url: string | null;
  medium_username: string | null;
  name: string;
  only_proxied_transfers: boolean;
  opensea_buyer_fee_basis_points: string;
  opensea_seller_fee_basis_points: string;
  payout_address: string | null;
  primary_asset_contracts: [];
  require_email: boolean;
  safelist_request_status: string;
  short_description: string | null;
  slug: string;
  stats: {
    average_price: number;
    count: number;
    floor_price: number;
    market_cap: number;
    num_owners: number;
    num_reports: number;
    one_day_average_price: number;
    one_day_change: number;
    one_day_sales: number;
    one_day_volume: number;
    seven_day_average_price: number;
    seven_day_change: number;
    seven_day_sales: number;
    seven_day_volume: number;
    thirty_day_average_price: number;
    thirty_day_change: number;
    thirty_day_sales: number;
    thirty_day_volume: number;
    total_sales: number;
    total_supply: number;
    total_volume: number;
  };
  telegram_url: string | null;
  traits: {};
  twitter_username: string | null;
  wiki_url: string | null;
}
